from .asu_air_image_generate import (
    NODE_CLASS_MAPPINGS as GENERATOR_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GENERATOR_DISPLAY_MAPPINGS,
)

from .asu_air_image_edit import (
    NODE_CLASS_MAPPINGS as EDITOR_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EDITOR_DISPLAY_MAPPINGS,
)

from .asu_air_video_generate import (
    NODE_CLASS_MAPPINGS as VIDEO_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {
    **GENERATOR_CLASS_MAPPINGS,
    **EDITOR_CLASS_MAPPINGS,
    **VIDEO_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GENERATOR_DISPLAY_MAPPINGS,
    **EDITOR_DISPLAY_MAPPINGS,
    **VIDEO_DISPLAY_MAPPINGS,
}
